<a href="https://colab.research.google.com/github/chandanaka07-design/AI-laborartory/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Load the Dataset
First, let's load the `Employee_dataset.csv` into a pandas DataFrame and display its initial information and the first few rows to understand its structure.

In [ ]:
import pandas as pd

# Load the dataset
df = pd.read_csv('/content/Employee_dataset.csv')

# Display basic information and the first few rows
print("Initial DataFrame Info:")
df.info()
print("\nInitial DataFrame Head:")
display(df.head())

Initial DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Employee_ID        1020 non-null   object
 1   First_Name         1020 non-null   object
 2   Last_Name          1020 non-null   object
 3   Age                809 non-null    float64
 4   Department_Region  1020 non-null   object
 5   Status             1020 non-null   object
 6   Join_Date          1020 non-null   object
 7   Salary             996 non-null    float64
 8   Email              1020 non-null   object
 9   Phone              1020 non-null   int64
 10  Performance_Score  1020 non-null   object
 11  Remote_Work        1020 non-null   bool
dtypes: bool(1), float64(2), int64(1), object(8)
memory usage: 88.8+ KB

Initial DataFrame Head:

,Employee_ID,First_Name,Last_Name,Age,Department_Region,Status,Join_Date,Salary,Email,Phone,Performance_Score,Remote_Work
0,EMP1000,Bob,Davis,25.0,DevOps-California,Active,04-02-2021,59767.65,bob.davis@example.com,-1651623197,Average,True
1,EMP1001,Bob,Brown,NaN,Finance-Texas,Active,07-10-2020,65304.66,bob.brown@example.com,-1898471390,Excellent,True
2,EMP1002,Alice,Jones,NaN,Admin-Nevada,Pending,12-07-2023,88145.90,alice.jones@example.com,-5596363211,Good,True
3,EMP1003,Eva,Davis,25.0,Admin-Nevada,Inactive,11/27/2021,69450.99,eva.davis@example.com,-3476490784,Good,True
4,EMP1004,Frank,Williams,25.0,Cloud Tech-Florida,Active,01-05-2022,109324.61,frank.williams@example.com,-1586734256,Poor,False

### Handle Duplicate Records
We'll identify and remove any exact duplicate rows in the dataset.

In [ ]:
print(f"Number of rows before removing duplicates: {len(df)}")
df.drop_duplicates(inplace=True)
print(f"Number of rows after removing duplicates: {len(df)}")
display(df.head())

Number of rows before removing duplicates: 1020
Number of rows after removing duplicates: 1020

,Employee_ID,First_Name,Last_Name,Age,Department_Region,Status,Join_Date,Salary,Email,Phone,Performance_Score,Remote_Work
0,EMP1000,Bob,Davis,25.0,DevOps-California,Active,04-02-2021,59767.65,bob.davis@example.com,-1651623197,Average,True
1,EMP1001,Bob,Brown,NaN,Finance-Texas,Active,07-10-2020,65304.66,bob.brown@example.com,-1898471390,Excellent,True
2,EMP1002,Alice,Jones,NaN,Admin-Nevada,Pending,12-07-2023,88145.90,alice.jones@example.com,-5596363211,Good,True
3,EMP1003,Eva,Davis,25.0,Admin-Nevada,Inactive,11/27/2021,69450.99,eva.davis@example.com,-3476490784,Good,True
4,EMP1004,Frank,Williams,25.0,Cloud Tech-Florida,Active,01-05-2022,109324.61,frank.williams@example.com,-1586734256,Poor,False

### Handle Missing Values
We'll check for missing values, especially in the 'Salary' column, and decide on an appropriate imputation strategy (e.g., fill with median for numerical columns).

In [ ]:
print("Missing values before imputation:")
display(df.isnull().sum())

# Convert 'Salary' to numeric, coercing errors to NaN
df['Salary'] = pd.to_numeric(df['Salary'], errors='coerce')

# Impute missing salaries with the median salary
median_salary = df['Salary'].median()
df['Salary'].fillna(median_salary, inplace=True)

print("\nMissing values after imputation:")
display(df.isnull().sum())
display(df.head())

Missing values before imputation:

Employee_ID            0
First_Name             0
Last_Name              0
Age                  211
Department_Region      0
Status                 0
Join_Date              0
Salary                24
Email                  0
Phone                  0
Performance_Score      0
Remote_Work            0
dtype: int64

Missing values after imputation:

/tmp/ipykernel_610/4008946027.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Salary'].fillna(median_salary, inplace=True)

Employee_ID            0
First_Name             0
Last_Name              0
Age                  211
Department_Region      0
Status                 0
Join_Date              0
Salary                 0
Email                  0
Phone                  0
Performance_Score      0
Remote_Work            0
dtype: int64

,Employee_ID,First_Name,Last_Name,Age,Department_Region,Status,Join_Date,Salary,Email,Phone,Performance_Score,Remote_Work
0,EMP1000,Bob,Davis,25.0,DevOps-California,Active,04-02-2021,59767.65,bob.davis@example.com,-1651623197,Average,True
1,EMP1001,Bob,Brown,NaN,Finance-Texas,Active,07-10-2020,65304.66,bob.brown@example.com,-1898471390,Excellent,True
2,EMP1002,Alice,Jones,NaN,Admin-Nevada,Pending,12-07-2023,88145.90,alice.jones@example.com,-5596363211,Good,True
3,EMP1003,Eva,Davis,25.0,Admin-Nevada,Inactive,11/27/2021,69450.99,eva.davis@example.com,-3476490784,Good,True
4,EMP1004,Frank,Williams,25.0,Cloud Tech-Florida,Active,01-05-2022,109324.61,frank.williams@example.com,-1586734256,Poor,False

### Inconsistent Date Formats
We'll convert any date columns (e.g., 'Hire_Date') to a consistent datetime format. I'll assume 'Hire_Date' is the relevant date column and try to infer its format.

In [ ]:
# Assuming a 'Hire_Date' column exists and needs conversion
# If a different date column name exists, please update 'Hire_Date'
if 'Hire_Date' in df.columns:
    df['Hire_Date'] = pd.to_datetime(df['Hire_Date'], errors='coerce')
    print("\n'Hire_Date' column after conversion:")
    display(df[['Hire_Date']].head())
    print(f"Number of invalid dates in 'Hire_Date' after conversion: {df['Hire_Date'].isnull().sum()}")
else:
    print("No 'Hire_Date' column found for date format conversion.")
display(df.info())

No 'Hire_Date' column found for date format conversion.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Employee_ID        1020 non-null   object
 1   First_Name         1020 non-null   object
 2   Last_Name          1020 non-null   object
 3   Age                809 non-null    float64
 4   Department_Region  1020 non-null   object
 5   Status             1020 non-null   object
 6   Join_Date          1020 non-null   object
 7   Salary             1020 non-null   float64
 8   Email              1020 non-null   object
 9   Phone              1020 non-null   int64
 10  Performance_Score  1020 non-null   object
 11  Remote_Work        1020 non-null   bool
dtypes: bool(1), float64(2), int64(1), object(8)
memory usage: 88.8+ KB

None

### Erroneous Entries (Non-numeric salary values)
We already handled non-numeric salary values by coercing them to `NaN` and then imputing, so the 'Salary' column should now be clean and numeric.

In [ ]:
print("Checking 'Salary' column data type after cleaning:")
display(df['Salary'].dtype)
display(df['Salary'].describe())

Checking 'Salary' column data type after cleaning:

dtype('float64')

count      1020.000000
mean      85164.299069
std       19638.385740
min       50047.320000
25%       68811.232500
50%       85547.870000
75%      100372.662500
max      119971.650000
Name: Salary, dtype: float64

### Compound Columns (e.g., 'Department_Region')
If there's a compound column like 'Department_Region' (e.g., 'Cloud Tech-Texas'), we'll split it into 'Department' and 'Region' columns.

In [ ]:
if 'Department_Region' in df.columns:
    # Split 'Department_Region' into 'Department' and 'Region'
    df[['Department', 'Region']] = df['Department_Region'].str.split('-', expand=True)
    print("\nDataFrame after splitting 'Department_Region':")
    display(df[['Department_Region', 'Department', 'Region']].head())
    # Optionally, drop the original compound column
    df.drop(columns=['Department_Region'], inplace=True)
else:
    print("No 'Department_Region' column found for splitting.")
display(df.head())

DataFrame after splitting 'Department_Region':

    Department_Region  Department      Region
0   DevOps-California      DevOps  California
1       Finance-Texas     Finance       Texas
2        Admin-Nevada       Admin      Nevada
3        Admin-Nevada       Admin      Nevada
4  Cloud Tech-Florida  Cloud Tech     Florida

,Employee_ID,First_Name,Last_Name,Age,Status,Join_Date,Salary,Email,Phone,Performance_Score,Remote_Work,Department,Region
0,EMP1000,Bob,Davis,25.0,Active,04-02-2021,59767.65,bob.davis@example.com,-1651623197,Average,True,DevOps,California
1,EMP1001,Bob,Brown,NaN,Active,07-10-2020,65304.66,bob.brown@example.com,-1898471390,Excellent,True,Finance,Texas
2,EMP1002,Alice,Jones,NaN,Pending,12-07-2023,88145.90,alice.jones@example.com,-5596363211,Good,True,Admin,Nevada
3,EMP1003,Eva,Davis,25.0,Inactive,11/27/2021,69450.99,eva.davis@example.com,-3476490784,Good,True,Admin,Nevada
4,EMP1004,Frank,Williams,25.0,Active,01-05-2022,109324.61,frank.williams@example.com,-1586734256,Poor,False,Cloud Tech,Florida

### Inconsistent Department Names
We'll standardize department names by converting them to a consistent case and stripping whitespace. We can also map common variations to a single name if needed (e.g., 'IT' and 'Information Technology').

In [ ]:
if 'Department' in df.columns:
    print("Original unique Department names:")
    display(df['Department'].unique())

    # Standardize department names (e.g., strip whitespace, title case)
    df['Department'] = df['Department'].str.strip().str.title()

    # Example: Mapping inconsistent names if they exist
    # department_mapping = {
    #     'It': 'Information Technology',
    #     'Hr': 'Human Resources'
    # }
    # df['Department'] = df['Department'].replace(department_mapping)

    print("\nCleaned unique Department names:")
    display(df['Department'].unique())
else:
    print("No 'Department' column found to standardize names.")
display(df.head())

Original unique Department names:

array(['DevOps', 'Finance', 'Admin', 'Cloud Tech', 'Sales', 'HR'],
      dtype=object)

Cleaned unique Department names:

array(['Devops', 'Finance', 'Admin', 'Cloud Tech', 'Sales', 'Hr'],
      dtype=object)

,Employee_ID,First_Name,Last_Name,Age,Status,Join_Date,Salary,Email,Phone,Performance_Score,Remote_Work,Department,Region
0,EMP1000,Bob,Davis,25.0,Active,04-02-2021,59767.65,bob.davis@example.com,-1651623197,Average,True,Devops,California
1,EMP1001,Bob,Brown,NaN,Active,07-10-2020,65304.66,bob.brown@example.com,-1898471390,Excellent,True,Finance,Texas
2,EMP1002,Alice,Jones,NaN,Pending,12-07-2023,88145.90,alice.jones@example.com,-5596363211,Good,True,Admin,Nevada
3,EMP1003,Eva,Davis,25.0,Inactive,11/27/2021,69450.99,eva.davis@example.com,-3476490784,Good,True,Admin,Nevada
4,EMP1004,Frank,Williams,25.0,Active,01-05-2022,109324.61,frank.williams@example.com,-1586734256,Poor,False,Cloud Tech,Florida

### Final Cleaned Dataset
Here's the information and a preview of the dataset after all cleaning and transformation steps.

In [ ]:
print("Final Cleaned DataFrame Info:")
df.info()
print("\nFinal Cleaned DataFrame Head:")
display(df.head())

Final Cleaned DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Employee_ID        1020 non-null   object
 1   First_Name         1020 non-null   object
 2   Last_Name          1020 non-null   object
 3   Age                809 non-null    float64
 4   Status             1020 non-null   object
 5   Join_Date          1020 non-null   object
 6   Salary             1020 non-null   float64
 7   Email              1020 non-null   object
 8   Phone              1020 non-null   int64
 9   Performance_Score  1020 non-null   object
 10  Remote_Work        1020 non-null   bool
 11  Department         1020 non-null   object
 12  Region             1020 non-null   object
dtypes: bool(1), float64(2), int64(1), object(9)
memory usage: 96.8+ KB

Final Cleaned DataFrame Head:

,Employee_ID,First_Name,Last_Name,Age,Status,Join_Date,Salary,Email,Phone,Performance_Score,Remote_Work,Department,Region
0,EMP1000,Bob,Davis,25.0,Active,04-02-2021,59767.65,bob.davis@example.com,-1651623197,Average,True,Devops,California
1,EMP1001,Bob,Brown,NaN,Active,07-10-2020,65304.66,bob.brown@example.com,-1898471390,Excellent,True,Finance,Texas
2,EMP1002,Alice,Jones,NaN,Pending,12-07-2023,88145.90,alice.jones@example.com,-5596363211,Good,True,Admin,Nevada
3,EMP1003,Eva,Davis,25.0,Inactive,11/27/2021,69450.99,eva.davis@example.com,-3476490784,Good,True,Admin,Nevada
4,EMP1004,Frank,Williams,25.0,Active,01-05-2022,109324.61,frank.williams@example.com,-1586734256,Poor,False,Cloud Tech,Florida